kind: ServiceAccount
apiVersion: v1
metadata:
  name: kiam-server
  namespace: kiam
  labels:
    app.kubernetes.io/name: kiam
    app.kubernetes.io/version: "3.0"
    app.kubernetes.io/component: server
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: kiam-read
  labels:
    app.kubernetes.io/name: kiam
    app.kubernetes.io/version: "3.0"
    app.kubernetes.io/component: server
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - pods
  verbs:
  - watch
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: kiam-read
  labels:
    app.kubernetes.io/name: kiam
    app.kubernetes.io/version: "3.0"
    app.kubernetes.io/component: server
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kiam-read
subjects:
- kind: ServiceAccount
  name: kiam-server
  namespace: kiam
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: kiam-write
  labels:
    app.kubernetes.io/name: kiam
    app.kubernetes.io/version: "3.0"
    app.kubernetes.io/component: server
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: kiam-write
  labels:
    app.kubernetes.io/name: kiam
    app.kubernetes.io/version: "3.0"
    app.kubernetes.io/component: server
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kiam-write
subjects:
- kind: ServiceAccount
  name: kiam-server
  namespace: kiam
---
apiVersion: v1
kind: Service
metadata:
  name: kiam-server
  namespace: kiam
  labels:
    app.kubernetes.io/name: kiam
    app.kubernetes.io/version: "3.0"
    app.kubernetes.io/component: server
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: kiam
    app.kubernetes.io/component: server
  ports:
  - name: grpclb
    port: 443
    targetPort: 443
    protocol: TCP
