apiVersion: v1
kind: Namespace
metadata:
  name: test
  annotations:
    iam.amazonaws.com/permitted: ${terraform_kiam_testrole_arn}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      annotations:
        iam.amazonaws.com/role: ${terraform_kiam_testrole_arn}
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
